name: Deploy 🚀
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
jobs:
  gh-pages-deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          version: 16.x

      - name: Cache node_modules
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/node_modules
          key: ${{ runner.os }}-node_modules

      - name: Install dependencies as CI
        run: npm ci

      - name: Webpack build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist

